language: scala

sudo: required

dist: precise

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/spark
    - $HOME/.sbt/launchers

jdk:
  - oraclejdk8

scala:
  - 2.10.4

before_install:
  - export PATH=$HOME/.local/bin:$PATH

script:
  - SPARK_CONF_DIR=./log4j/ ./sbt/sbt clean test

notifications:
  email:
    recipients:
      - dawid.rutowicz@gmail.com